/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ft_encrypt_Encrypt */

#ifndef _Included_com_ft_encrypt_Encrypt
#define _Included_com_ft_encrypt_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ft_encrypt_Encrypt
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ft_encrypt_Encrypt_encrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
